# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Release
on:
  push:
    tags:
      - "*"
      - "!*-rc*"
concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: write
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Download RC contents
        run: |
          set -x
          latest_rc_tag=$(gh release list --json tagName --jq '.[].tagName' | \
                            grep -F "${GITHUB_REF_NAME}-rc" | \
                            head -n1)
          gh release download ${latest_rc_tag} --dir dists
      - name: Create GitHub Release
        run: |
          # GH-499: How to create release notes?
          version=${GITHUB_REF_NAME#v}
          gh release create ${GITHUB_REF_NAME} \
            --generate-notes \
            --title "Apache Arrow Java ${version}" \
            --verify-tag \
            dists/*
